export const cardData = [
    {
        id: 1,
        backgroundColor: "#9e9e9f",
        img:"/model1A.png",
        title: "Hoodies & Sweatshirts",
        price:"$65.22",
        rating:2,
        
    },
    {
        id: 2,
        backgroundColor: "#8569a4",
        img:"/model2A.png",
        title: "Coats & Parkas",
        price:"$13.24",
        rating:3,
    },
    {
        id: 3,
        backgroundColor: "#93cfcf",
        img:"/model3A.png",
        title: "Tees & T-Shirts",
        price:"$19.96",
        rating:4,
    },
    {
        id: 4,
        backgroundColor: "#819ab3",
        img:"/model4A.png",
        title: "Sleeveless Hoodies",
        price:"$26.11",
        rating:3,
    },
    {
        id: 5,
        backgroundColor: "#edbac2",
        img:"/model5A.png",
        title: "Henley shirts",
        price:"$23.22",
        rating:5
    },
    {
        id: 6,
        backgroundColor: "#c2d09b",
        img:"/model6A.png",
        title: "Crewneck & Sweaters",
        price:"$10.99",
        rating:4,
    },
    {
        id: 7,
        backgroundColor: "#A45A03",
        img:"/model20.png",
        title: "Graphic tees",
        price:"$65.12",
        rating:4,
    },
    {
        id: 8,
        backgroundColor: "#232C33",
        img:"/model8.png",
        title: "Crewneck & Sweaters",
        price:"$11.76",
        rating:3,
    },
    {
        id: 9,
        backgroundColor: "#71ACD7",
        img:"/model10.png",
        title: "Polo Shirts",
        price:"$45.21",
        rating:3,
    },
    {
        id: 10,
        backgroundColor: "#E0E3E8",
        img:"/model11.png",
        title: "Cardigans",
        price:"$20.03",
        rating:2,
    },
    {
        id:11,
        backgroundColor: "#F5B31E",
        img:"/model12.png",
        title: "V-Neck Sweaters",
        price:"$33.32",
        rating:4,
    },
    {
        id: 12,
        backgroundColor: "#F8989C",
        img:"/model13.png",
        title: "Zip-Up Hoodies",
        price:"$18.77",
        rating:5,
    },
    {
        id: 13,
        backgroundColor: "#03988E",
        img:"/model14.png",
        title: "Flannel Shirts",
        price:"$17.77",
        rating:3,
    },
    {
        id: 14,
        backgroundColor: "#EEAAB7",
        img:"/model15.png",
        title: "Long-sleeve t-shirts",
        price:"$29.77",
        rating:2,
    },
    {
        id: 15,
        backgroundColor: "#FFD10F",
        img:"/model16.png",
        title: "Tank Tops",
        price:"$30.77",
        rating:1,
    },
    {
        id: 16,
        backgroundColor: "#2EBBED",
        img:"/model17.png",
        title: "Puffer Vest",
        price:"$41.77",
        rating:3,
    }
]